name: Build and Deploy Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image with Docker Compose
        run: docker compose -f docker-compose.yml build
      - name: Tag the model
        run: docker tag tp1_mlops-api ${{ secrets.DOCKERHUB_USERNAME }}/mlops1
      - name: Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Production
        run: sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }}
      - name: Docker pull
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mlops1
      - name: Docker
        run: docker run -p 8016:8016 ${{ secrets.DOCKERHUB_USERNAME }}/mlops1
