name: Build and Deploy Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image with Docker Compose
        run: docker compose -f docker-compose.yml build
      - name: Tag the model
        run: docker tag tp1_mlops-api ${{ secrets.DOCKERHUB_USERNAME }}/mlops1
      - name: Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker compose pull ${{ secrets.DOCKERHUB_USERNAME }}/mlops1
            docker compose up -d
