name: Build and Deploy Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image with Docker Compose
        run: docker compose -f docker-compose.yml build
      - name: Tag the model
        run: docker tag tp1_mlops-api ${{ secrets.DOCKERHUB_USERNAME }}/tp1_mlops-api
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tp1_mlops-api

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/ubuntu
            docker compose pull ${{ secrets.DOCKERHUB_USERNAME }}/tp1_mlops-api
            docker compose up -d
